// ==================== i18n SYSTEM ====================
const i18n = {
  languages: {
    en: { flag: '🇬🇧', label: 'EN' },
    tr: { flag: '🇹🇷', label: 'TR' },
    th: { flag: '🇹🇭', label: 'TH' },
  },

  translations: {
    en: {
      // Splash
      splash_tagline: 'same questions. blind answers. one reveal.',
      splash_get_started: 'get started',
      splash_have_account: 'i have an account',
      // Onboarding
      onboarding_title: 'how it works',
      onboarding_step1_title: 'pick a pack',
      onboarding_step1_desc: 'choose a question pack that matches your vibe',
      onboarding_step2_title: 'answer privately',
      onboarding_step2_desc: 'both of you answer the same questions — no peeking',
      onboarding_step3_title: 'reveal together',
      onboarding_step3_desc: 'answers unlock only when you\'ve both submitted',
      onboarding_cta: 'let\'s go',
      // Home
      home_all: 'All',
      home_active: 'Active',
      home_completed: 'Completed',
      home_invite_sent: 'invite sent',
      home_new_session: '+ new session',
      home_loading: 'loading...',
      home_no_sessions: 'no sessions yet — start one!',
      home_with: 'with',
      home_waiting_partner: 'waiting for partner',
      home_done: 'done',
      home_load_error: 'could not load sessions',
      home_with_alex: 'with Alex',
      home_with_jordan: 'with Jordan',
      home_with_taylor_match: 'with Taylor · 83% match',
      badge_reveal: 'Reveal!',
      badge_progress: 'In progress',
      badge_waiting: 'Waiting',
      // Pack names
      pack_couples: 'Couples Edition',
      pack_bestfriends: 'Best Friends',
      pack_deeptalk: 'Deep Talk',
      pack_coworkers: 'Coworkers',
      pack_36questions: '36 Questions to Fall in Love',
      pack_friendship_deep_dive: 'Friendship Deep Dive',
      // Pack counts
      pack_count_couples: '10 questions',
      pack_count_bestfriends: '8 questions',
      pack_count_deeptalk: '12 questions',
      pack_count_coworkers: '5 questions',
      pack_count_36questions: '36 questions · based on Arthur Aron\'s study',
      pack_hottakes: 'Hot Takes',
      pack_redflags: 'Red Flag or Nah',
      pack_chaotic: 'Chaotic Energy',
      pack_count_hottakes: '10 questions · spicy opinions only',
      pack_count_redflags: '10 questions · judge freely',
      pack_count_chaotic: '10 questions · unhinged vibes',
      pack_fungames: 'Fun & Games',
      pack_worldtaste: 'World & Taste',
      pack_ethics: 'Ethics & Dilemmas',
      pack_situations: 'Situations',
      pack_livingtogether: 'Living Together',
      pack_soulspirit: 'Soul & Spirit',
      pack_count_fungames: '10 questions · lighthearted fun',
      pack_count_worldtaste: '10 questions · culture & flavors',
      pack_count_ethics: '10 questions · moral crossroads',
      pack_count_situations: '10 questions · react to life',
      pack_count_livingtogether: '10 questions · cohabitation vibes',
      pack_count_soulspirit: '10 questions · meaning & belief',
      pack_desc_fungames: 'lighthearted chaos. no wrong answers.',
      pack_desc_worldtaste: 'travel, food, culture — how worldly are you?',
      pack_desc_situations: 'real-life moments. how would you actually react?',
      // Nav
      nav_home: 'Home',
      nav_packs: 'Decks',
      // Packs
      packs_subtitle: 'pick one, send it, see what happens',
      packs_trending: 'trending now',
      packs_all: 'all packs',
      packs_played: 'played',
      // Pack descriptions (featured cards)
      pack_desc_36questions: 'the viral study that makes strangers fall in love. are you brave enough?',
      pack_desc_hottakes: 'spicy opinions only. no fence-sitting allowed.',
      pack_desc_redflags: 'judge each other\'s takes. no mercy.',
      // Category filters
      cat_all: 'All',
      cat_love: 'Love',
      cat_friends: 'Friends',
      cat_spicy: 'Spicy',
      cat_deep: 'Deep',
      cat_work: 'Work',
      cat_culture: 'Culture',
      cat_lifestyle: 'Lifestyle',
      cat_self: 'Self',
      // Collections
      packs_collections: 'collections',
      coll_decks: 'decks',
      coll_date_night: 'Date Night',
      coll_desc_date_night: 'the perfect bundle for couples who want to go deeper',
      coll_spicy_edition: 'Spicy Edition',
      coll_desc_spicy_edition: 'hot takes, red flags & chaos — all in one pack',
      coll_deep_bonds: 'Deep Bonds',
      coll_desc_deep_bonds: 'meaningful conversations that actually matter',
      coll_friend_zone: 'Friend Zone',
      coll_desc_friend_zone: 'fun & real talk for you and your bestie',
      coll_culture_taste: 'Culture & Taste',
      coll_desc_culture_taste: 'travel, beliefs & lifestyle — how aligned are you?',
      coll_send_to_him: 'Send to Him',
      coll_desc_send_to_him: 'archetype quizzes to take about your partner & share',
      coll_know_yourself: 'Know Yourself',
      coll_desc_know_yourself: 'personality, shadow, boundaries — the full inner deep dive',
      coll_love_decoded: 'Love Decoded',
      coll_desc_love_decoded: 'attachment, love language & your relationship patterns',
      coll_relationship_xray: 'Relationship X-Ray',
      coll_desc_relationship_xray: 'see through the dynamics — couple story, hidden truths & more',
      coll_inner_work: 'Inner Work',
      coll_desc_inner_work: 'stress, sabotage & shadow — the hard stuff that heals',
      // Solo packs
      pack_attachment: 'Attachment Style',
      pack_innermirror: 'Inner Mirror',
      pack_stresstype: 'Stress Response',
      pack_count_attachment: '10 questions · how you love',
      pack_count_innermirror: '10 questions · who you really are',
      pack_count_stresstype: '10 questions · fight, flight, freeze or fawn',
      pack_desc_attachment: 'discover your attachment style. no partner needed.',
      pack_desc_innermirror: 'a mirror into your personality. just you.',
      // Solo results
      solo_badge: 'Solo',
      solo_your_result: 'your result',
      solo_dominant_trait: 'dominant trait',
      solo_breakdown: 'full breakdown',
      solo_take_another: 'take another test',
      solo_you_probably: 'you probably...',
      solo_note_to_self: 'note to self',
      mode_partner: 'Partner',
      mode_self: 'Self',
      // New solo packs
      pack_lovelang: 'Love Language',
      pack_shadow: 'Shadow Self',
      pack_emotionalage: 'Emotional Age',
      pack_boundaries: 'Boundary Check',
      pack_selfsabotage: 'Self-Sabotage',
      pack_count_lovelang: '10 questions · how you give & receive love',
      pack_count_shadow: '10 questions · what you hide from yourself',
      pack_count_emotionalage: '10 questions · how old is your inner self',
      pack_count_boundaries: '10 questions · walls, filters, or open doors',
      pack_count_selfsabotage: '10 questions · why you get in your own way',
      pack_desc_lovelang: 'based on the 5 love languages. warning: may cause feelings.',
      pack_desc_emotionalage: 'not your age — your emotional age. they\'re rarely the same.',
      // Character archetype decks
      pack_hisarchetype: 'His Archetype',
      pack_girlfriendera: 'Girlfriend Era',
      pack_couplestory: 'Couple Story',
      pack_whathehides: 'What He Hides',
      pack_count_hisarchetype: '10 questions · what type is he?',
      pack_count_girlfriendera: '10 questions · what era are you in?',
      pack_count_couplestory: '10 questions · your couple dynamic',
      pack_count_whathehides: '10 questions · his unspoken truths',
      pack_desc_hisarchetype: 'golden retriever or chaos king? find out his archetype.',
      pack_desc_girlfriendera: 'main character, healer, ride or die, or soft villain?',
      pack_desc_couplestory: 'soulmates, adventure duo, chaos couple, or slow burn?',
      pack_desc_whathehides: 'the things he feels but never says out loud.',
      // Badges
      badge_trending: 'Trending',
      badge_viral: 'Viral',
      badge_hot: 'Hot',
      badge_new: 'New',
      badge_popular: 'Popular',
      'badge_new-badge': 'New',
      // Marquee
      marquee_trending: 'Trending now',
      marquee_plays: '50k+ rounds played',
      marquee_new: '3 new packs',
      marquee_dare: 'dare to be honest?',
      marquee_viral: 'Going viral',
      marquee_send: 'send it to your person',
      // Invite
      invite_title: 'share with your person',
      invite_desc: 'they\'ll get the same questions. no one sees answers until you both finish.',
      invite_copy: 'copy',
      invite_simulate: 'simulate: partner joins →',
      // Quiz
      quiz_back: 'back',
      quiz_next: 'next',
      quiz_submit: 'submit',
      quiz_question: 'question',
      bubble_hint: 'tap all that apply',
      swipe_hint: 'pick all that fit',
      // Waiting
      waiting_title: 'you\'re locked in 🔒',
      waiting_desc: 'waiting for <strong style="color:var(--text)">Alex</strong> to finish answering...',
      waiting_progress: 'Alex is on question 3 of 5',
      waiting_nudge: '👉 send a nudge',
      waiting_simulate: 'simulate: partner done →',
      // Modal
      modal_title: 'lock in your answers?',
      modal_desc: 'once you submit, no take-backs. your person will be notified you\'re done.',
      modal_confirm: 'lock it in',
      modal_cancel: 'wait, go back',
      // Settings
      settings_mode: 'Mode',
      settings_accent: 'Accent Color',
      // Results
      results_matches: 'matches',
      results_plot_twists: 'plot twists',
      results_sync_rate: 'sync rate',
      results_share: '📤 share this vibe check',
      results_play_another: 'play another pack',
      results_back_home: 'back home',
      results_you: 'you',
      results_of: 'of',
      // Reveal
      reveal_question_of: 'question {n} of {total}',
      reveal_you: 'You',
      reveal_tap_reveal: 'tap to reveal',
      reveal_tap_continue: 'tap to continue →',
      reveal_get_ready: 'get ready',
      // Feedback
      feedback_copied: 'copied!',
      feedback_nudge_sent: '✅ nudge sent!',
      feedback_link_copied: '✅ link copied!',
      // Delete
      delete_title: 'remove this session?',
      delete_desc: 'this will remove the session from your list. this can\'t be undone.',
      delete_confirm: 'remove',
      delete_cancel: 'cancel',
      delete_label: 'Delete',
    },

    tr: {
      splash_tagline: 'aynı sorular. gizli cevaplar. bir açılış.',
      splash_get_started: 'başla',
      splash_have_account: 'hesabım var',
      onboarding_title: 'nasıl çalışır',
      onboarding_step1_title: 'bir paket seç',
      onboarding_step1_desc: 'tarzına uyan bir soru paketi seç',
      onboarding_step2_title: 'gizlice cevapla',
      onboarding_step2_desc: 'ikiniz de aynı soruları cevaplıyorsunuz — gözetleme yok',
      onboarding_step3_title: 'birlikte aç',
      onboarding_step3_desc: 'cevaplar ancak ikiniz de gönderdikten sonra açılır',
      onboarding_cta: 'hadi başlayalım',
      home_all: 'Tümü',
      home_active: 'Aktif',
      home_completed: 'Tamamlanan',
      home_invite_sent: 'davet gönderildi',
      home_new_session: '+ yeni oturum',
      home_loading: 'yükleniyor...',
      home_no_sessions: 'henüz oturum yok — bir tane başlat!',
      home_with: 'ile',
      home_waiting_partner: 'partner bekleniyor',
      home_done: 'tamamlandı',
      home_load_error: 'oturumlar yüklenemedi',
      home_with_alex: 'Alex ile',
      home_with_jordan: 'Jordan ile',
      home_with_taylor_match: 'Taylor ile · %83 eşleşme',
      badge_reveal: 'Aç!',
      badge_progress: 'Devam ediyor',
      badge_waiting: 'Bekliyor',
      pack_couples: 'Çiftler Paketi',
      pack_bestfriends: 'En İyi Arkadaşlar',
      pack_deeptalk: 'Derin Sohbet',
      pack_coworkers: 'İş Arkadaşları',
      pack_36questions: 'Aşık Olmak İçin 36 Soru',
      pack_friendship_deep_dive: 'Arkadaşlık Analizi',
      pack_count_couples: '10 soru',
      pack_count_bestfriends: '8 soru',
      pack_count_deeptalk: '12 soru',
      pack_count_coworkers: '5 soru',
      pack_count_36questions: '36 soru · Arthur Aron\'un çalışmasına dayanır',
      pack_hottakes: 'Keskin Yorumlar',
      pack_redflags: 'Red Flag mı Değil mi',
      pack_chaotic: 'Kaotik Enerji',
      pack_count_hottakes: '10 soru · sadece cesur fikirler',
      pack_count_redflags: '10 soru · yargıla rahatça',
      pack_count_chaotic: '10 soru · çılgın vibes',
      pack_fungames: 'Eğlence & Oyunlar',
      pack_worldtaste: 'Dünya & Lezzetler',
      pack_ethics: 'Etik & İkilemler',
      pack_situations: 'Durumlar',
      pack_livingtogether: 'Birlikte Yaşam',
      pack_soulspirit: 'Ruh & Mana',
      pack_count_fungames: '10 soru · hafif eğlence',
      pack_count_worldtaste: '10 soru · kültür & tatlar',
      pack_count_ethics: '10 soru · ahlaki kavşaklar',
      pack_count_situations: '10 soru · hayata tepki ver',
      pack_count_livingtogether: '10 soru · ev arkadaşlığı',
      pack_count_soulspirit: '10 soru · anlam & inanç',
      pack_desc_fungames: 'hafif kaos. yanlış cevap yok.',
      pack_desc_worldtaste: 'seyahat, yemek, kültür — ne kadar dünya vatandaşısın?',
      pack_desc_situations: 'gerçek hayat anları. gerçekten nasıl tepki verirdin?',
      nav_home: 'Ana Sayfa',
      nav_packs: 'Paketler',
      packs_subtitle: 'birini seç, gönder, neler olacak gör',
      packs_trending: 'şu an trend',
      packs_all: 'tüm paketler',
      packs_played: 'oynandı',
      pack_desc_36questions: 'yabancıları aşık eden viral çalışma. cesaret eder misin?',
      pack_desc_hottakes: 'sadece keskin fikirler. çit üstü yok.',
      pack_desc_redflags: 'birbirinizi yargılayın. merhamet yok.',
      cat_all: 'Tümü',
      cat_love: 'Aşk',
      cat_friends: 'Arkadaş',
      cat_spicy: 'Ateşli',
      cat_deep: 'Derin',
      cat_work: 'İş',
      cat_culture: 'Kültür',
      cat_lifestyle: 'Yaşam',
      cat_self: 'Kendin',
      packs_collections: 'koleksiyonlar',
      coll_decks: 'deste',
      coll_date_night: 'Randevu Gecesi',
      coll_desc_date_night: 'derinleşmek isteyen çiftler için mükemmel paket',
      coll_spicy_edition: 'Acı Versiyon',
      coll_desc_spicy_edition: 'hot take, red flag & kaos — hepsi bir arada',
      coll_deep_bonds: 'Derin Bağlar',
      coll_desc_deep_bonds: 'gerçekten önemli olan anlamlı sohbetler',
      coll_friend_zone: 'Arkadaş Bölgesi',
      coll_desc_friend_zone: 'sen ve en yakın arkadaşın için eğlence & gerçek konuşma',
      coll_culture_taste: 'Kültür & Zevk',
      coll_desc_culture_taste: 'seyahat, inançlar & yaşam tarzı — ne kadar uyumlusunuz?',
      coll_send_to_him: 'Ona Gönder',
      coll_desc_send_to_him: 'partneriniz hakkında çözüp paylaşacağınız arketip testleri',
      coll_know_yourself: 'Kendini Tanı',
      coll_desc_know_yourself: 'kişilik, gölge, sınırlar — tam bir iç keşif',
      coll_love_decoded: 'Aşk Çözümlendi',
      coll_desc_love_decoded: 'bağlanma, aşk dili & ilişki kalıpların',
      coll_relationship_xray: 'İlişki Röntgeni',
      coll_desc_relationship_xray: 'dinamikleri gör — çift hikayesi, gizli gerçekler & daha fazlası',
      coll_inner_work: 'İç Çalışma',
      coll_desc_inner_work: 'stres, sabotaj & gölge — iyileştiren zor şeyler',
      pack_attachment: 'Bağlanma Stili',
      pack_innermirror: 'İç Ayna',
      pack_stresstype: 'Stres Tepkisi',
      pack_count_attachment: '10 soru · nasıl seviyorsun',
      pack_count_innermirror: '10 soru · gerçekte kim olduğun',
      pack_count_stresstype: '10 soru · savaş, kaç, don veya uy',
      pack_desc_attachment: 'bağlanma stilini keşfet. partner gerekmiyor.',
      pack_desc_innermirror: 'kişiliğine bir ayna. sadece sen.',
      solo_badge: 'Solo',
      solo_your_result: 'sonucun',
      solo_dominant_trait: 'baskın özellik',
      solo_breakdown: 'tam analiz',
      solo_take_another: 'başka test yap',
      solo_you_probably: 'muhtemelen sen...',
      solo_note_to_self: 'kendine not',
      mode_partner: 'Partner',
      mode_self: 'Kendin',
      pack_lovelang: 'Sevgi Dili',
      pack_shadow: 'Gölge Ben',
      pack_emotionalage: 'Duygusal Yaş',
      pack_boundaries: 'Sınır Kontrolü',
      pack_selfsabotage: 'Kendini Sabote',
      pack_count_lovelang: '10 soru · nasıl seviyorsun',
      pack_count_shadow: '10 soru · kendinden sakladıkların',
      pack_count_emotionalage: '10 soru · iç dünyanın yaşı',
      pack_count_boundaries: '10 soru · duvarlar, filtreler, açık kapılar',
      pack_count_selfsabotage: '10 soru · neden kendi önüne geçiyorsun',
      pack_desc_lovelang: '5 sevgi diline dayalı. uyarı: duygulara neden olabilir.',
      pack_desc_emotionalage: 'yaşın değil — duygusal yaşın. nadiren aynıdır.',
      pack_hisarchetype: 'Onun Arketipi',
      pack_girlfriendera: 'Kız Arkadaş Dönemi',
      pack_couplestory: 'Çift Hikayesi',
      pack_whathehides: 'Sakladıkları',
      pack_count_hisarchetype: '10 soru · o hangi tip?',
      pack_count_girlfriendera: '10 soru · hangi dönemdesin?',
      pack_count_couplestory: '10 soru · çift dinamiğiniz',
      pack_count_whathehides: '10 soru · söylenmeyen gerçekler',
      pack_desc_hisarchetype: 'golden retriever mı kaos kralı mı? arketipini keşfet.',
      pack_desc_girlfriendera: 'ana karakter, şifacı, ölümüne sadık, yoksa yumuşak kötü?',
      pack_desc_couplestory: 'ruh eşleri, macera ikilisi, kaos çifti, yoksa yavaş yanan aşk?',
      pack_desc_whathehides: 'hissedip hiç söylemediği şeyler.',
      badge_trending: 'Trend',
      badge_viral: 'Viral',
      badge_hot: 'Popüler',
      badge_new: 'Yeni',
      badge_popular: 'Sevilen',
      'badge_new-badge': 'Yeni',
      marquee_trending: 'Şu an trend',
      marquee_plays: '50k+ tur oynandı',
      marquee_new: '3 yeni paket',
      marquee_dare: 'dürüst olmaya cesaretin var mı?',
      marquee_viral: 'Viral oluyor',
      marquee_send: 'kişine gönder',
      invite_title: 'kişinle paylaş',
      invite_desc: 'aynı soruları alacak. ikiniz de bitirene kadar kimse cevapları göremez.',
      invite_copy: 'kopyala',
      invite_simulate: 'simülasyon: partner katılıyor →',
      quiz_back: 'geri',
      quiz_next: 'ileri',
      quiz_submit: 'gönder',
      quiz_question: 'soru',
      bubble_hint: 'uygun olanların hepsine dokun',
      swipe_hint: 'uyanların hepsini seç',
      waiting_title: 'kilitlendin 🔒',
      waiting_desc: '<strong style="color:var(--text)">Alex</strong>\'in cevaplaması bekleniyor...',
      waiting_progress: 'Alex 5 sorudan 3. soruda',
      waiting_nudge: '👉 dürt',
      waiting_simulate: 'simülasyon: partner bitti →',
      modal_title: 'cevaplarını kilitle?',
      modal_desc: 'gönderdikten sonra geri dönüş yok. kişine bildirim gidecek.',
      modal_confirm: 'kilitle',
      modal_cancel: 'dur, geri dön',
      settings_mode: 'Mod',
      settings_accent: 'Vurgu Rengi',
      results_matches: 'eşleşme',
      results_plot_twists: 'sürpriz',
      results_sync_rate: 'uyum oranı',
      results_share: '📤 vibe check\'i paylaş',
      results_play_another: 'başka paket oyna',
      results_back_home: 'ana sayfaya dön',
      results_you: 'sen',
      results_of: '/',
      reveal_question_of: 'soru {n} / {total}',
      reveal_you: 'Sen',
      reveal_tap_reveal: 'açmak için dokun',
      reveal_tap_continue: 'devam için dokun →',
      reveal_get_ready: 'hazır ol',
      feedback_copied: 'kopyalandı!',
      feedback_nudge_sent: '✅ dürtü gönderildi!',
      feedback_link_copied: '✅ link kopyalandı!',
      delete_title: 'bu oturumu kaldır?',
      delete_desc: 'bu oturumu listenden kaldıracak. bu işlem geri alınamaz.',
      delete_confirm: 'kaldır',
      delete_cancel: 'iptal',
      delete_label: 'Sil',
    },

    th: {
      splash_tagline: 'คำถามเดียวกัน คำตอบลับ เปิดเผยพร้อมกัน',
      splash_get_started: 'เริ่มเลย',
      splash_have_account: 'ฉันมีบัญชีแล้ว',
      onboarding_title: 'วิธีใช้งาน',
      onboarding_step1_title: 'เลือกชุดคำถาม',
      onboarding_step1_desc: 'เลือกชุดคำถามที่เข้ากับคุณ',
      onboarding_step2_title: 'ตอบแบบส่วนตัว',
      onboarding_step2_desc: 'ทั้งคู่ตอบคำถามเดียวกัน — ห้ามแอบดู',
      onboarding_step3_title: 'เปิดเผยด้วยกัน',
      onboarding_step3_desc: 'คำตอบจะเปิดเผยเมื่อทั้งสองคนส่งแล้วเท่านั้น',
      onboarding_cta: 'เริ่มเลย',
      home_all: 'ทั้งหมด',
      home_active: 'กำลังดำเนินการ',
      home_completed: 'เสร็จสิ้น',
      home_invite_sent: 'ส่งคำเชิญแล้ว',
      home_new_session: '+ เซสชันใหม่',
      home_loading: 'กำลังโหลด...',
      home_no_sessions: 'ยังไม่มีเซสชัน — เริ่มเลย!',
      home_with: 'กับ',
      home_waiting_partner: 'รอคู่หู',
      home_done: 'เสร็จแล้ว',
      home_load_error: 'ไม่สามารถโหลดเซสชันได้',
      home_with_alex: 'กับ Alex',
      home_with_jordan: 'กับ Jordan',
      home_with_taylor_match: 'กับ Taylor · ตรงกัน 83%',
      badge_reveal: 'เปิดเผย!',
      badge_progress: 'กำลังทำ',
      badge_waiting: 'รอ',
      pack_couples: 'คู่รัก',
      pack_bestfriends: 'เพื่อนซี้',
      pack_deeptalk: 'คุยลึก',
      pack_coworkers: 'เพื่อนร่วมงาน',
      pack_36questions: '36 คำถามเพื่อตกหลุมรัก',
      pack_friendship_deep_dive: 'เจาะลึกมิตรภาพ',
      pack_count_couples: '10 คำถาม',
      pack_count_bestfriends: '8 คำถาม',
      pack_count_deeptalk: '12 คำถาม',
      pack_count_coworkers: '5 คำถาม',
      pack_count_36questions: '36 คำถาม · อ้างอิงจากงานวิจัยของ Arthur Aron',
      pack_hottakes: 'ความเห็นแรง',
      pack_redflags: 'Red Flag หรือเปล่า',
      pack_chaotic: 'พลังวุ่นวาย',
      pack_count_hottakes: '10 คำถาม · ความเห็นแบบจัดจ้าน',
      pack_count_redflags: '10 คำถาม · ตัดสินได้เลย',
      pack_count_chaotic: '10 คำถาม · ไวบ์บ้าบอ',
      pack_fungames: 'สนุก & เกม',
      pack_worldtaste: 'โลก & รสชาติ',
      pack_ethics: 'จริยธรรม & ทางเลือก',
      pack_situations: 'สถานการณ์',
      pack_livingtogether: 'อยู่ด้วยกัน',
      pack_soulspirit: 'จิตวิญญาณ',
      pack_count_fungames: '10 คำถาม · สนุกเบาๆ',
      pack_count_worldtaste: '10 คำถาม · วัฒนธรรม & รสชาติ',
      pack_count_ethics: '10 คำถาม · ทางแยกศีลธรรม',
      pack_count_situations: '10 คำถาม · ตอบสนองต่อชีวิต',
      pack_count_livingtogether: '10 คำถาม · ชีวิตร่วมกัน',
      pack_count_soulspirit: '10 คำถาม · ความหมาย & ความเชื่อ',
      pack_desc_fungames: 'ความวุ่นวายเบาๆ ไม่มีคำตอบผิด',
      pack_desc_worldtaste: 'ท่องเที่ยว อาหาร วัฒนธรรม — คุณรู้จักโลกแค่ไหน?',
      pack_desc_situations: 'ช่วงเวลาในชีวิตจริง คุณจะตอบสนองยังไง?',
      nav_home: 'หน้าแรก',
      nav_packs: 'ชุดคำถาม',
      packs_subtitle: 'เลือกชุด ส่งไป แล้วดูผลลัพธ์',
      packs_trending: 'กำลังฮิต',
      packs_all: 'ชุดทั้งหมด',
      packs_played: 'เล่นแล้ว',
      pack_desc_36questions: 'งานวิจัยไวรัลที่ทำให้คนแปลกหน้าตกหลุมรัก กล้าไหม?',
      pack_desc_hottakes: 'ความเห็นแบบจัดจ้านเท่านั้น ห้ามอยู่กลางๆ',
      pack_desc_redflags: 'ตัดสินกันเลย ไม่ต้องเกรงใจ',
      cat_all: 'ทั้งหมด',
      cat_love: 'รัก',
      cat_friends: 'เพื่อน',
      cat_spicy: 'แซ่บ',
      cat_deep: 'ลึก',
      cat_work: 'งาน',
      cat_culture: 'วัฒนธรรม',
      cat_lifestyle: 'ไลฟ์สไตล์',
      cat_self: 'ตัวเอง',
      packs_collections: 'คอลเลกชัน',
      coll_decks: 'สำรับ',
      coll_date_night: 'คืนเดท',
      coll_desc_date_night: 'แพ็กสมบูรณ์แบบสำหรับคู่รักที่อยากรู้จักกันลึกขึ้น',
      coll_spicy_edition: 'เผ็ดร้อน',
      coll_desc_spicy_edition: 'ความเห็นแรง ธงแดง & ความวุ่นวาย — ครบในแพ็กเดียว',
      coll_deep_bonds: 'สายสัมพันธ์ลึก',
      coll_desc_deep_bonds: 'บทสนทนาที่มีความหมายจริงๆ',
      coll_friend_zone: 'โซนเพื่อน',
      coll_desc_friend_zone: 'สนุก & คุยจริงจังกับเพื่อนซี้',
      coll_culture_taste: 'วัฒนธรรม & รสนิยม',
      coll_desc_culture_taste: 'เที่ยว ความเชื่อ & ไลฟ์สไตล์ — เข้ากันแค่ไหน?',
      coll_send_to_him: 'ส่งให้เขา',
      coll_desc_send_to_him: 'แบบทดสอบอาร์คีไทป์เกี่ยวกับคนรักของคุณ & แชร์ผล',
      coll_know_yourself: 'รู้จักตัวเอง',
      coll_desc_know_yourself: 'บุคลิกภาพ เงามืด ขอบเขต — ดำดิ่งสู่ภายในอย่างเต็มที่',
      coll_love_decoded: 'ถอดรหัสความรัก',
      coll_desc_love_decoded: 'ความผูกพัน ภาษารัก & รูปแบบความสัมพันธ์ของคุณ',
      coll_relationship_xray: 'เอ็กซ์เรย์ความสัมพันธ์',
      coll_desc_relationship_xray: 'มองทะลุพลวัต — เรื่องราวคู่ ความจริงที่ซ่อน & อีกมากมาย',
      coll_inner_work: 'งานภายใน',
      coll_desc_inner_work: 'ความเครียด การทำลายตัวเอง & เงามืด — สิ่งยากที่เยียวยา',
      pack_attachment: 'สไตล์ความผูกพัน',
      pack_innermirror: 'กระจกภายใน',
      pack_stresstype: 'การตอบสนองต่อความเครียด',
      pack_count_attachment: '10 คำถาม · คุณรักแบบไหน',
      pack_count_innermirror: '10 คำถาม · ตัวตนที่แท้จริง',
      pack_count_stresstype: '10 คำถาม · สู้ หนี แข็ง หรือตาม',
      pack_desc_attachment: 'ค้นพบสไตล์ความผูกพัน ไม่ต้องมีคู่',
      pack_desc_innermirror: 'กระจกส่องบุคลิกภาพ แค่คุณ',
      solo_badge: 'เดี่ยว',
      solo_your_result: 'ผลลัพธ์ของคุณ',
      solo_dominant_trait: 'ลักษณะเด่น',
      solo_breakdown: 'วิเคราะห์ทั้งหมด',
      solo_take_another: 'ทำแบบทดสอบอื่น',
      solo_you_probably: 'คุณอาจจะ...',
      solo_note_to_self: 'โน้ตถึงตัวเอง',
      mode_partner: 'คู่หู',
      mode_self: 'ตัวเอง',
      pack_lovelang: 'ภาษารัก',
      pack_shadow: 'ตัวตนที่ซ่อน',
      pack_emotionalage: 'อายุทางอารมณ์',
      pack_boundaries: 'เช็คขอบเขต',
      pack_selfsabotage: 'ทำลายตัวเอง',
      pack_count_lovelang: '10 คำถาม · คุณให้และรับความรักยังไง',
      pack_count_shadow: '10 คำถาม · สิ่งที่ซ่อนจากตัวเอง',
      pack_count_emotionalage: '10 คำถาม · ตัวตนข้างในอายุเท่าไหร่',
      pack_count_boundaries: '10 คำถาม · กำแพง ฟิลเตอร์ หรือประตูเปิด',
      pack_count_selfsabotage: '10 คำถาม · ทำไมถึงขวางตัวเอง',
      pack_desc_lovelang: 'อิงจาก 5 ภาษารัก เตือน: อาจทำให้เกิดความรู้สึก',
      pack_desc_emotionalage: 'ไม่ใช่อายุคุณ — อายุทางอารมณ์ แทบไม่เคยเท่ากัน',
      pack_hisarchetype: 'อาร์คีไทป์ของเขา',
      pack_girlfriendera: 'ยุคแฟนสาว',
      pack_couplestory: 'เรื่องราวคู่รัก',
      pack_whathehides: 'สิ่งที่เขาซ่อน',
      pack_count_hisarchetype: '10 คำถาม · เขาเป็นแบบไหน?',
      pack_count_girlfriendera: '10 คำถาม · คุณอยู่ในยุคไหน?',
      pack_count_couplestory: '10 คำถาม · ไดนามิกของคู่คุณ',
      pack_count_whathehides: '10 คำถาม · ความจริงที่ไม่เคยพูด',
      pack_desc_hisarchetype: 'โกลเด้นรีทรีฟเวอร์หรือราชาแห่งความวุ่นวาย? ค้นหาอาร์คีไทป์ของเขา',
      pack_desc_girlfriendera: 'ตัวละครหลัก, ผู้เยียวยา, ตายด้วยกัน, หรือวายร้ายอ่อนโยน?',
      pack_desc_couplestory: 'เนื้อคู่, คู่ผจญภัย, คู่วุ่นวาย, หรือรักค่อยเป็นค่อยไป?',
      pack_desc_whathehides: 'สิ่งที่เขารู้สึกแต่ไม่เคยพูดออกมา',
      badge_trending: 'ฮิต',
      badge_viral: 'ไวรัล',
      badge_hot: 'ฮอต',
      badge_new: 'ใหม่',
      badge_popular: 'ยอดนิยม',
      'badge_new-badge': 'ใหม่',
      marquee_trending: 'กำลังฮิต',
      marquee_plays: '50k+ รอบที่เล่น',
      marquee_new: '3 ชุดใหม่',
      marquee_dare: 'กล้าพูดตรงไหม?',
      marquee_viral: 'กำลังไวรัล',
      marquee_send: 'ส่งให้คนของคุณ',
      invite_title: 'แชร์ให้คนของคุณ',
      invite_desc: 'พวกเขาจะได้คำถามเดียวกัน ไม่มีใครเห็นคำตอบจนกว่าทั้งคู่จะตอบเสร็จ',
      invite_copy: 'คัดลอก',
      invite_simulate: 'จำลอง: คู่หูเข้าร่วม →',
      quiz_back: 'กลับ',
      quiz_next: 'ถัดไป',
      quiz_submit: 'ส่ง',
      quiz_question: 'คำถาม',
      bubble_hint: 'แตะทุกข้อที่ตรง',
      swipe_hint: 'เลือกทุกข้อที่ใช่',
      waiting_title: 'คุณพร้อมแล้ว 🔒',
      waiting_desc: 'รอ <strong style="color:var(--text)">Alex</strong>...',
      waiting_progress: 'Alex ตอบถึงข้อ 3 จาก 5',
      waiting_nudge: '👉 เตือน',
      waiting_simulate: 'จำลอง: คู่หูตอบเสร็จ →',
      modal_title: 'ยืนยันคำตอบ?',
      modal_desc: 'เมื่อส่งแล้วจะแก้ไม่ได้ คู่หูของคุณจะได้รับแจ้ง',
      modal_confirm: 'ยืนยัน',
      modal_cancel: 'เดี๋ยวก่อน กลับไป',
      settings_mode: 'โหมด',
      settings_accent: 'สีเน้น',
      results_matches: 'ตรงกัน',
      results_plot_twists: 'เซอร์ไพรส์',
      results_sync_rate: 'อัตราซิงค์',
      results_share: '📤 แชร์ไวบ์เช็ค',
      results_play_another: 'เล่นชุดอื่น',
      results_back_home: 'กลับหน้าแรก',
      results_you: 'คุณ',
      results_of: 'จาก',
      reveal_question_of: 'คำถาม {n} จาก {total}',
      reveal_you: 'คุณ',
      reveal_tap_reveal: 'แตะเพื่อเปิดเผย',
      reveal_tap_continue: 'แตะเพื่อไปต่อ →',
      reveal_get_ready: 'เตรียมตัว',
      feedback_copied: 'คัดลอกแล้ว!',
      feedback_nudge_sent: '✅ เตือนแล้ว!',
      feedback_link_copied: '✅ คัดลอกลิงก์แล้ว!',
      delete_title: 'ลบเซสชันนี้?',
      delete_desc: 'เซสชันจะถูกลบออกจากรายการของคุณ ไม่สามารถย้อนกลับได้',
      delete_confirm: 'ลบ',
      delete_cancel: 'ยกเลิก',
      delete_label: 'ลบ',
    },
  },

  current: localStorage.getItem('bs-lang') || 'en',

  t(key) {
    return this.translations[this.current]?.[key]
      || this.translations.en[key]
      || key;
  },

  setLanguage(lang) {
    if (!this.translations[lang]) return;
    this.current = lang;
    localStorage.setItem('bs-lang', lang);
    document.documentElement.setAttribute('lang', lang);
    this.applyAll();
    this.renderSelector();
    if (typeof updateLangCycleBtn === 'function') updateLangCycleBtn();
    // Re-render dynamic content
    if (typeof renderPacksGrid === 'function') renderPacksGrid();
    if (typeof renderHomeSessions === 'function' && currentScreen === 'home') renderHomeSessions();
    if (typeof getQuestions === 'function') {
      questions = getQuestions(selectedPackKey || 'couples');
    }
  },

  applyAll() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      const val = this.t(key);
      if (el.innerHTML !== val) el.innerHTML = val;
    });
  },

  renderSelector() {
    const container = document.getElementById('langSelector');
    if (!container) return;
    container.innerHTML = Object.entries(this.languages).map(([code, { flag, label }]) =>
      `<button class="lang-btn ${code === this.current ? 'active' : ''}" onclick="i18n.setLanguage('${code}')">
        <span class="lang-flag">${flag}</span>${label}
      </button>`
    ).join('');
  },

  init() {
    document.documentElement.setAttribute('lang', this.current);
    this.applyAll();
    this.renderSelector();
    if (typeof updateLangCycleBtn === 'function') updateLangCycleBtn();
  }
};

function cycleLang() {
  const codes = Object.keys(i18n.languages);
  const idx = codes.indexOf(i18n.current);
  const next = codes[(idx + 1) % codes.length];
  i18n.setLanguage(next);
}

function updateLangCycleBtn() {
  const flag = document.getElementById('langCycleFlag');
  if (flag) flag.textContent = i18n.languages[i18n.current]?.flag || '🌐';
}
